### ISSUE TITLE
rename-file doesn't rename fully qualified function references

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#173]
I had a `with-redefs` in my test ns and when I moved the ns with the functions being mocked out the weren't renamed properly.

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by vemv** [comment]
@expez: by any chance you'd like to give a go to this issue and perhaps other related work?

With https://github.com/clojure-emacs/refactor-nrepl/commit/622c210ccbca3eb9f9be5ff72816d096b1042d48, renaming files is working again.

I'm enjoying it already but I suspect there might be missing edge cases here and there e.g. metadata, Clojure's newer syntaxes for ns-qualified things, etc.

Especially since only the updated rewrite-clj has proper support for some of those.

Obviously it's just a suggestion, can give it a shot myself at some point.

**Comment by expez** [comment]
> I'm enjoying it already but I suspect there might be missing edge cases here and there e.g. metadata, Clojure's newer syntaxes for ns-qualified things, etc.

This is very likely!

> by any chance you'd like to give a go to this issue and perhaps other related work?

I have very limited time for open source work lately, but we do get some time at work to spend on side projects.  I've been trying to put that time into refactor-nrepl, but had to cut a new release for [superstring](https://github.com/expez/superstring) last time around.

Will def try to spend more time here.  It's for sure more fun now that you're here breathing new life and enthusiasm into the project 🤗

**Comment by vemv** [comment]
🍻 thanks for the answer, let's see how it goes!

**Comment by vemv** [comment]
I took a look at `refactor-nrepl.rename-file-or-dir`, it doesn't use rewrite-clj so perhaps I wouldn't push this specific impl much more. `string/replace` can only buy us so much...

I'd look into integrating clojure-lsp's programmatic api, it doesn't involve running a lsp server at all so we save that complexity.

see e.g. https://cljdoc.org/d/com.github.clojure-lsp/clojure-lsp/2021.11.02-15.24.47/api/clojure-lsp.api#rename! (that renames a symbol, not a file/dir)

As mentioned in some other issue, it's a good idea to introduce a protocol so we all can use what we find best.

**Comment by vemv** [comment]
After researching, clojure-lsp is right now bit of a dense dep to pull (it has lots of transitive deps). They're open to a modularization but probably it's not something to expect too soon.

Which invited me to think, refactor-nrepl's `string/replace` impl isn't so bad after all. In terms of false negative (should have refactored, didn't refactor) I'd expect them to be absent, even for metadata or fancy constructs.

In terms of false positives (refactored where it shouldn't have: comments, strings, quoted symbols maybe?), those are harder to parse against, OTOH discerning users will review refactor-nrepl's results. That's why VCS, unit tests etc exist :)

So I'd keep/extend the current impl indefinitely, seems good to have something self-contained.

Will give it a shot eventually if nobody else beats me to it 👀
