### ISSUE TITLE
[Feature request] Provide access to individual functions of `clean-ns`

### ISSUE THREAD

**Issue by daveliepmann** [clojure-emacs/refactor-nrepl#190]
My cljr-refactor workflow used to include `remove-unused-requires` but I am not interested in the rest of `clean-ns`. Is it possible, or would it be feasible and acceptable, to provide *a la carte* access to the functions that constitute `clean-ns`? 

I ask because it seems like it was an intentional design decision to remove this kind of access to individual functions, per https://github.com/clojure-emacs/refactor-nrepl/issues/7#issuecomment-63105488.

**Comment by expez** [comment]
> My cljr-refactor workflow used to include `remove-unused-requires` but I am not interested in the rest of `clean-ns`

Why aren't you interested in the rest of `clean-ns`?  

There are already settings to change the behavior to

* Don't prune, just sort stuff.
* Don't rewrite to prefix form.

What's missing from your point of view?

**Comment by daveliepmann** [comment]
Because I don't want to use someone else's highly opinionated style guide. I don't want your sorting rules. Sometimes, despite being an anti-`:use` zealot, I want to use `:use`. Having settings to prevent rewriting to prefix form is nice, but this is a general issue: I don't want to introduce *in one atomic step* N different changes to my namespace that make seeing those N changes difficult to read/notice/distinguish.

All I want is for unused requires to be removed.

In the abstract, I think *a la carte* access to constituent functions of a combined cleanup function is generally the best architectural approach. I'm not aware if these constituent functions are private for some practical reason. But my immediate workflow desire is access to `remove-unused-requires` and nothing else.

**Comment by expez** [comment]
Thanks for taking the time to explain what is that you want.  Unfortunately this isn't something that I'd be interested in working on.  It would be hours of work and the corresponding clj-refactor changes would, in my view, take us in the wrong direction.

The way I think of the ns form is that it's there for the compiler, and no human should ever have to interact with it directly, other than to resolve names when doing code review.  This is why we removed three clj-refactor functions in favor of one monolith which does everything, so you don't ever have to.  

I'm now at the point where I don't even see the diff in ns forms, because I know the tooling has that covered.  If you did java before clojure I'm sure you too stopped seeing the import diffs after a while, because you know intellij has your back.

FWIW, you should be able to just put `remove-unused-requires` in your `.emacs` and be back to the workflow you prefer.  It doesn't require the middleware.
