### ISSUE TITLE
Don't generate prefix lists for cljs files

### ISSUE THREAD

**Issue by bsteuber** [clojure-emacs/refactor-nrepl#191]
ClojureScript doesn't allow for prefix lists in :require clauses, but running cljr-rename-file-or-dir creates them nontheless.

## Expected behavior

For .cljs files, generate ns forms like 

    (ns foo.bar
      (:require [foo.baz.bar :as bar]
                [foo.baz.baz :as baz]))

## Actual behavior

It generates

    (ns foo.bar
      (:require [foo.baz
                 [bar :as bar]
                 [baz :as baz]]))

## Steps to reproduce the problem

- have a setup like above in ClojureScript
- do cider-jack-in-clojurescript
- call cljr-rename-file-or-dir on e.g. goo/baz/bar.cljs and rename it
- the foo.bar ns form now was rebuilt like above

### clj-refactor.el and refactor-nrepl version information

```
clj-refactor 2.3.0-SNAPSHOT (package: 20170126.118), refactor-nrepl 2.3.0-SNAPSHOT
```

### CIDER version information

```
CIDER 0.15.0snapshot (package: 20170129.1941), nREPL 0.2.12
Clojure 1.8.0, Java 1.8.0_121
```
### Leiningen or Boot version

```
Leiningen 2.5.3
```

### Emacs version

25.1

### Operating system

*E.g. Fedora 23, OS X 10.11 "El Capitan", Windows 10, etc*

**Comment by benedekfazekas** [comment]
i guess this is `clean-ns` really. As a workaround you can `(setq cljr-favor-prefix-notation nil)`

**Comment by magnars** [comment]
I genuinely don't understand why prefix notation is the default. It's not the suggested style in the style guide, it's not implemented in cljs, and per @expez' own words - you shouldn't be manually crafting the requires either, which is what the prefix notation optimizes for.

I'd say the proper fix for this issue is to change the default.

**Comment by benedekfazekas** [comment]
I have this switched off as long as i remember too. +1 for making sans prefix notation the default

**Comment by expez** [comment]
> which is what the prefix notation optimizes for

I think it increases readability, by making everything more dense.

> I genuinely don't understand why prefix notation is the default.

I regret the default now, because it violates the 'greppability principle'.  If you want to know where some ns is used, you can't grep for the name if it's in prefix notation.

> I'd say the proper fix for this issue is to change the default.

We should probably change the default, but unless we're going to drop the setting entirely the proper fix is to pass the right override for cljs files, like we do for clean-ns.

**Comment by bsteuber** [comment]
Thanks for the workaround :) But yeah changing the default sounds like a
good idea.

**Comment by benedekfazekas** [comment]
defalut was changed in clojure-emacs/clj-refactor.el#373. keep this open as an override would still make sense for cljs

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by expez** [comment]
This was fixed a while back, but this we forgot to reference / close this issue.
