### ISSUE TITLE
find-symbol doesn't work on macros

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#47]

**Comment by benedekfazekas** [comment]
i would argue this is a know limitation and solving it would be an enhancement. but just my 5c...

deffo top prio for next bigish release

**Comment by benedekfazekas** [comment]
just sharing some of my notes/thoughts on this as it is not trivial and finding a simple enough solution will be hard ;)

two sides of the macro problem for find symbols (and all features based on on it):

1. macros are not found when find-symbol is run
   example: `let` not found, `assert` not found

1. as they are expanded occurrences of stuff **is** found in what they are expanded into
   example: `str` is found wherever there is an `assert` (but `str` is **not** present there in the source)

root cause: they are expanded before the AST build which is necessary to have a AST which represents code that compiles.

**Comment by benedekfazekas** [comment]
#79 is basically 2.

**Comment by tsdh** [comment]
IIUC, one bad side-effect of this issue is that `cljr-clean-ns` will silently remove requires for namespaces from which only macros are used.

**Comment by expez** [comment]
We handle macros using a different mechanism in `clean-ns`.  It should be able to handle this situation.  If you have reproducible situation I'd love a bug report!

**Comment by tsdh** [comment]
@expez Ok, I'll try to create one.
