### ISSUE TITLE
getting "error in process filter: ..... is in bad state!" when using the refactor-nrepl middleware and features

### ISSUE THREAD

**Issue by gdanov** [clojure-emacs/refactor-nrepl#74]
I keep getting that exception (with valid namespace filled in) without any further details. The project compiles without problem so I am baffled what is it that the refactor lib dislikes about the namespace.

Where/how can I understand what prevents the AST tree to be built?

**Comment by expez** [comment]
Unfortunately the stacktraces produced by `tools.analyzer.jvm` are some of the most horrific stacktraces the clojure ecosystem has to offer.  

If you wan to take a look at the stacktrace anyway, you can use `cider-find-ns` (or just open the jar in `~/.m2` or wherever you're storing your mvn artifacts) to inspect `refactor-nrepl.analyzer` and edit the following function:

```clj
(defn ns-ast
  "Build AST for a namespace"
  [file-content]
  (try
    (cachable-ast file-content)
    (catch Exception ex
      (throw (IllegalStateException.
              (str (first (parse-ns file-content)) " is in a bad state!"))))))
```

to this:

```clj
(defn ns-ast
  "Build AST for a namespace"
  [file-content]
    (cachable-ast file-content))
```

and the evaluate  it.

If you now run `cljr-clean-ns` or `cljr-find-symbol` you should get the stacktrace dumped into the repl.

I've experienced problems with namespaces instrumented with [spyscope](https://github.com/dgrnbrg/spyscope) but otherwise there are no known bugs in this area.

**Comment by benedekfazekas** [comment]
@expez wonder if we should add a verbose flag in the next release and show the root cause if that is on. what do u think?

**Comment by expez** [comment]
Yeah, that might be a good idea

**Comment by gdanov** [comment]
that would be of great help. Enabling the traces as advised above helped me fix the problem. Without them it's frustrating guessing game.

emacs has some great utilities for presenting more usable clojure stack traces — maybe this could help.

**Comment by benedekfazekas** [comment]
just out of curiosity: what was causing the problem?

**Comment by gdanov** [comment]
cross-ns reference I believe. After I saw the exception I managed to cause large scale damage trying to clean-up the namespaces in the project via refactor and this was another yak shaving session. I am still beginner with emacs so I do that...
