### ISSUE TITLE
rename-file-or-dir doesn't work with boot

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/refactor-nrepl#97]
from discussion with @mitchelkuijpers on slack

> Does anyone know how to make clj-refactor behave with src/clj and src/cljs?
> but when i try  the rename-file-or-directory command I get an error like this:
> 
> ```
> cljr--maybe-rethrow-error: Can't find src dir prefix for path /users/mitkuijp/development/relations_for_jira/src/clj/relations_for_jira/companies/companies.clj
> ```

the corresponding project file:

``` clojure
(defproject relations-for-jira "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.7.0"     :scope "provided"]
                 [adzerk/boot-cljs      "0.0-2814-4" :scope "test"]
                 [adzerk/boot-reload    "0.3.1"      :scope "test"]
                 [danielsz/boot-environ "0.0.3" :scope "test"]

                 ;; server
                 [environ"1.0.0"]
                 [org.danielsz/system "0.1.8"]
                 [aleph "0.4.0"]
                 [yada "0.4.3"]
                 [org.clojure/tools.nrepl "0.2.10"]
                 [cheshire "5.5.0"]
                 [enlive "1.1.5"]

                                        ; Datomic
                 [com.datomic/datomic-pro "0.9.5067" :exclusions [[org.slf4j/slf4j-nop]
                                                                  [org.slf4j/slf4j-log4j12]]]
                                        ; Datomic schema management
                 [io.rkn/conformity "0.3.5"]

                                        ; logging
                 [org.clojure/tools.logging "0.3.1"]
                 [ch.qos.logback/logback-classic "1.1.3"]

                 ;; json web token
                 [clj-jwt "0.0.13"]
                 [pandect "0.5.2"]
                 [buddy "0.5.5"]

                 ;; client
                 [org.clojure/clojurescript "0.0-3308" :scope "provided"]
                 [cljs-ajax "0.3.13" :scope "provided" :exclusions [clj-time]]
                 [secretary "1.2.3" :scope "provided"]
                 [re-frame "0.4.1" :exclusions [[org.clojure/clojurescript]
                                                [org.clojure/clojure]] :scope "provided"]]
  :source-paths ["src/clj" "src/cljs"]
  :resource-paths ["resources"])
```

**Comment by Malabarba** [comment]
This reminds me, in a project of mine with a similar setup I get a problem with the auto generated ns form. The form will contain the initial `clj` in its namespace, but it shouldn't. 

I Figured it's probably the same issue, so I'm posting here instead of creating a new one.

**Comment by expez** [comment]
@Malabarba that would be something else and actually a bug in `clojure-mode` as we rely on `clojure-expected-ns` to provide us with the name of the ns.

**Comment by expez** [comment]
@mitchelkuijpers I can't reproduce this.  

I created a new test project with `src/clj` and `src/cljs` and preceded to rename two files `core.clj` and `foo.clj` where `foo` depends on `core`. I then moved `core.clj` and `foo.clj`, one by one, into a new dir `src/clj/core` which I then renamed.  Everything worked as expected.

Could you provide a minimal example displaying the problem you're having?

**Comment by mitchelkuijpers** [comment]
@expez I'll get back to you with an example tommorow I'll see if I can reproduce this in a small example project

**Comment by mitchelkuijpers** [comment]
@expez 

It seems to work with leiningen but not with boot. I created a little sample project https://github.com/mitchelkuijpers/clj-refactor-boot-project if you run ```lein repl``` and rename ```bar.clj``` to ```foo.clj``` it works. If you run boot repl and try the same thing it fails with aforementioned error

```
cljr--maybe-rethrow-error: Can't find src dir prefix for path /users/mitkuijp/development/relations_for_jira/src/clj/relations_for_jira/companies/companies.clj
```

**Comment by expez** [comment]
Hi @mitchelkuijpers thanks for adding some more information.

In order to find the ns of the file I'm about to create I have to get rid of the prefix in the file path which represents the path to the source directory.  Instead of assuming that this is `src`, or `test`, I find this prefix by examining directories and source files on the classpath.  

The problem occurs because boot doesn't put your src files on the classpath, instead it adds a copy of your src directory in some temp folder to the cp.

I'm sure they had a good reason for doing this, but now I need a new algorithm for finding the name of the new ns, given these new constraints, and nothing comes to mind.

Suggestions welcome!

**Comment by mitchelkuijpers** [comment]
Hi @expez 

Now I get it, i'll check the boot slack channel and see if these guys can come up with a solution. I'll try to come up with a pull request to fix this issue.

**Comment by Deraen** [comment]
https://github.com/clojure-emacs/refactor-nrepl/blob/master/src/refactor_nrepl/rename_file_or_dir.clj#L30

Boot sets sets the `fake.class.path` property to point to the original folders, so a solution would be to use that if it is set.

Though better solution would be do handle this in tools.namespace and java.classpath.

**Comment by micha** [comment]
This might be helpful to explain what the `fake.class.path` and `boot.class.path` system properties represent. https://github.com/boot-clj/boot/blob/a4d5f3bcbedc2e756c75dbfb8b43a5f5d396f81a/boot/core/src/boot/core.clj#L117-L128

**Comment by micha** [comment]
Note that a given file in the project `:source-paths`, say `com/me/myproject/core.clj` might not have the same contents as the corresponding `com/me/myproject/core.clj` file that's on the classpath! This is because in boot tasks can actually modify or delete any file in the project. This is also why boot doesn't use files from `:source-paths` or `:resource-paths` directly---it copies them into temp directories so that tasks can molest them without destroying the project. The fileset abstraction provides the mechanism by which tasks can create new, modified file trees in a way similar to persistent collections (i.e. the fileset object itself is an immutable snapshot of the classpath and project and anyone can hold a reference to it, calling `commit!` on the fileset synchronizes the actual mutable filesystem and classpath with the immutable fileset).

**Comment by benedekfazekas** [comment]
@micha any comment on boot-clj/boot#249 I am a bit reluctant to add boot specific to the actual implementations of features tbh. no idea what @bbatsov thinks about the cider side of things...

**Comment by expez** [comment]
The list of ops that are using the classpath without taking `boot` into account is: `find-usages`, `extract-definition`, `find-unbound`, `clean-ns` and `rename-file-or-dir`.

Since all these ops are basically working tentatively, and by accident, my first instinct is to just drop boot support until this is fixed.  Yet people seem to have been using `refactor-nrepl` with boot for some time now, which makes me think that would be an overreaction. Can you guys help answer if this is so bad that we should stop advertising boot support until it's fixed?

None of the current maintainers are using boot, which makes this a pretty shit problem to have.

**Comment by micha** [comment]
@benedekfazekas I see the relationship between files in the filesystem and resources on the classpath as being a very tooling-specific kind of thing, anyway. The JVM provides no mechanism for correctly tracking this kind of configuration, so the provenance of various resources needs to be worked out with the help of whichever tool configured the JVM, no?

**Comment by micha** [comment]
@benedekfazekas We can implement an API in boot for mapping resources to original files, if that would help?

**Comment by benedekfazekas** [comment]
fair point. however, these assumptions work quite well in practice, well apart from boot atm... any chance boot could *optionally* do the usual thing with the classpath for those tooling projects which need this?

**Comment by benedekfazekas** [comment]
haha it seems i just proposed the same thing. would be ace :)

**Comment by micha** [comment]
Excellent, I'll make a boot issue to track this and link back here.

**Comment by benedekfazekas** [comment]
:+1: thanks!

**Comment by micha** [comment]
Please feel free to comment on the issue if you have time :)

**Comment by benedekfazekas** [comment]
new snapshot is on clojars
